"""
bootstrap_cron_jobs — Idempotently register all ultra-workshop Hermes cron jobs.

This Hermes build has no `cronjob()` skill builtin and no `hermes skill run`
subcommand (the previous implementation relied on both and silently no-op'd on
every install). Instead this is a plain script that:

  1. Writes a thin bash wrapper per cron skill into ~/.hermes/scripts/. Each
     wrapper cd's to the deployed hermes-skills dir and execs the in-place
     skill under the Hermes venv python (so `import brain_http` and the
     venv-installed `workshop` package both resolve).
  2. Registers each job via `hermes cron create <schedule> --name <name>
     --no-agent --script <wrapper>.sh`, skipping any job whose name already
     exists (idempotent — safe to re-run on every install).

Run during installation via the Hermes venv python (NOT `hermes skill run`):
  sudo -u uws /opt/ultra-workshop/hermes/venv/bin/python \
    /opt/ultra-workshop/hermes-skills/bootstrap_cron_jobs.py

Env overrides: HERMES_BIN, UWS_VENV_PYTHON, UWS_SKILLS_DIR, HERMES_SCRIPTS_DIR.

Deploy location: /opt/ultra-workshop/hermes-skills/bootstrap_cron_jobs.py
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s [bootstrap_cron_jobs] %(message)s",
)
logger = logging.getLogger(__name__)

INSTALL_DIR = os.environ.get("UWS_INSTALL_DIR", "/opt/ultra-workshop")
SKILLS_DIR = os.environ.get("UWS_SKILLS_DIR", f"{INSTALL_DIR}/hermes-skills")
VENV_PYTHON = os.environ.get("UWS_VENV_PYTHON", f"{INSTALL_DIR}/hermes/venv/bin/python")
HERMES_BIN = os.environ.get("HERMES_BIN", f"{INSTALL_DIR}/hermes/venv/bin/hermes")
SCRIPTS_DIR = Path(os.environ.get("HERMES_SCRIPTS_DIR", str(Path.home() / ".hermes" / "scripts")))

# name → (schedule, target skill module run in-place under the venv)
_CRON_JOBS = [
    {"name": "daily-research", "schedule": "0 7 * * *", "skill": "cron_daily_research"},
    {"name": "nightly-tests", "schedule": "0 2 * * *", "skill": "cron_nightly_tests"},
    {"name": "bug-scan-standard", "schedule": "0 */4 * * *", "skill": "cron_standard_poll"},
    {"name": "nightly-rescan", "schedule": "0 3 * * *", "skill": "cron_standard_poll"},
]


def _write_wrapper(skill: str) -> str:
    """Write (or refresh) the bash wrapper for a skill; return its filename."""
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    fname = f"{skill}.sh"
    target = SCRIPTS_DIR / fname
    content = (
        "#!/usr/bin/env bash\n"
        f"# Auto-generated by bootstrap_cron_jobs.py — runs {skill}.py in place under the Hermes venv.\n"
        "set -euo pipefail\n"
        f"cd {SKILLS_DIR}\n"
        f"exec {VENV_PYTHON} {SKILLS_DIR}/{skill}.py\n"
    )
    target.write_text(content, encoding="utf-8")
    target.chmod(0o755)
    return fname


def _existing_job_names() -> set[str]:
    """Parse `hermes cron list` for already-registered job names (idempotency)."""
    try:
        out = subprocess.run(
            [HERMES_BIN, "cron", "list"],
            capture_output=True, text=True, timeout=30, check=False,
        ).stdout
    except (OSError, subprocess.SubprocessError) as exc:
        logger.warning("Could not list existing cron jobs (%s) — proceeding without dedup", exc)
        return set()
    names = set()
    for line in out.splitlines():
        s = line.strip()
        if s.startswith("Name:"):
            names.add(s.split(":", 1)[1].strip())
    return names


def register_cron_jobs() -> int:
    existing = _existing_job_names()
    created = 0
    for job in _CRON_JOBS:
        name = job["name"]
        # Always (re)write the wrapper — cheap and keeps it in sync even if a job
        # already exists but its wrapper was removed.
        wrapper = _write_wrapper(job["skill"])
        if name in existing:
            logger.info("Cron job already registered — skipping create: %s", name)
            continue
        logger.info("Registering cron job: %s (schedule=%s, script=%s)", name, job["schedule"], wrapper)
        result = subprocess.run(
            [HERMES_BIN, "cron", "create", job["schedule"],
             "--name", name, "--no-agent", "--script", wrapper],
            capture_output=True, text=True, timeout=60, check=False,
        )
        if result.returncode != 0:
            logger.error("Failed to register %s: %s", name, (result.stderr or result.stdout)[:300])
        else:
            logger.info("Registered: %s", name)
            created += 1
    logger.info("Bootstrap complete: %d created, %d already present", created, len(_CRON_JOBS) - created)
    return 0


if __name__ == "__main__":
    sys.exit(register_cron_jobs())
