# Deploy location: /opt/ultra-workshop/hermes-skills/workshop_push.py
# Run as: sudo -u uws /opt/ultra-workshop/hermes/venv/bin/python3 /opt/ultra-workshop/hermes-skills/workshop_push.py
"""
workshop_push — post-approval git push + gh pr create + ADR write-back.

Called by skills/pr-opener/SKILL.md via terminal python3 AFTER the SKILL.md body
has already received HITL approval from the user. The approval gate lives in the
calling SKILL.md body, not here.

SECURITY: All subprocess calls use shell=False. GH_TOKEN is injected from env
(GITHUB_PAT env var), never hardcoded.

ADR frontmatter uses dotted-namespace keys:
  workshop.task_id, workshop.status, workshop.pr_url, system.created_by, date
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Load brain_http.py via importlib (non-blocking — None if absent)
# ---------------------------------------------------------------------------
_BRAIN_HTTP = Path(__file__).parent / "brain_http.py"
_brain_http = None
try:
    _spec = importlib.util.spec_from_file_location("brain_http", _BRAIN_HTTP)
    _brain_http = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_brain_http)
except Exception as _exc:
    print(f"[workshop_push] WARNING: brain_http not loaded: {_exc}", file=sys.stderr, flush=True)


def _read_text_arg(value: str, file_path: str, *, label: str) -> str:
    if not file_path:
        return value
    try:
        return Path(file_path).read_text(encoding="utf-8").rstrip("\n")
    except OSError as exc:
        print(f"[workshop_push] ERROR: {label} file error: {exc}", flush=True)
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Post-approval: git push + gh pr create + ADR write-back.",
    )
    parser.add_argument("--task-id", required=True, help="Workshop task ID")
    parser.add_argument("--branch", required=True, help="Git branch to push (e.g. workshop/<task-id>)")
    parser.add_argument("--workspace-dir", required=True, help="Absolute path to the cloned target repo workspace")
    parser.add_argument("--repo-full-name", default="caiobellizzi/test-workshop-sandbox", help="GitHub owner/name for PR creation")
    parser.add_argument("--base", default="main", help="Base branch for PR creation")
    parser.add_argument("--plan-goal", default="", help="Original task goal (used in PR title and ADR)")
    parser.add_argument("--plan-goal-file", default="", help="Path containing the original task goal")
    parser.add_argument("--diff-summary", default="", help="Aider diff summary (used in PR body and ADR)")
    parser.add_argument("--diff-summary-file", default="", help="Path containing the aider diff summary")
    args = parser.parse_args()

    task_id = args.task_id
    branch = args.branch
    workspace_dir = args.workspace_dir
    repo_full_name = args.repo_full_name
    base_branch = args.base
    plan_goal = _read_text_arg(args.plan_goal, args.plan_goal_file, label="plan goal")
    diff_summary = _read_text_arg(args.diff_summary, args.diff_summary_file, label="diff summary")

    # STEP 1 — git push
    push_result = subprocess.run(
        ["git", "push", "origin", branch],
        cwd=workspace_dir,
        capture_output=True,
        text=True,
        shell=False,
        env={**os.environ, "GH_TOKEN": os.environ.get("GITHUB_PAT", "")},
    )
    if push_result.returncode != 0:
        print(f"[workshop_push] ERROR: git push failed: {push_result.stderr}", flush=True)
        sys.exit(1)

    # STEP 2 — gh pr create
    pr_title = f"[workshop/{task_id}] {plan_goal[:60]}"
    pr_body = (
        f"Auto-generated by ultra-workshop.\n\n"
        f"Task: {task_id}\n\n"
        f"{diff_summary[:400]}"
    )
    pr_result = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", repo_full_name,
            "--base", base_branch,
            "--head", branch,
            "--title", pr_title,
            "--body", pr_body,
        ],
        capture_output=True,
        text=True,
        shell=False,
        env={**os.environ, "GH_TOKEN": os.environ.get("GITHUB_PAT", "")},
    )
    if pr_result.returncode != 0:
        print(f"[workshop_push] ERROR: gh pr create failed: {pr_result.stderr}", flush=True)
        sys.exit(1)
    pr_url = pr_result.stdout.strip()
    print(f"[workshop_push] PR opened: {pr_url}", flush=True)

    # STEP 3 — ADR write-back (non-blocking try/except)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    adr_path = f"vault/_system/workshop-adrs/{task_id}.md"
    adr_content = (
        f"---\n"
        f"workshop.task_id: {task_id}\n"
        f"workshop.repo: {repo_full_name}\n"
        f"workshop.base_branch: {base_branch}\n"
        f"workshop.status: done\n"
        f"workshop.pr_url: {pr_url}\n"
        f"system.created_by: workshop\n"
        f"date: {today}\n"
        f"---\n\n"
        f"# ADR: {task_id}\n\n"
        f"**Goal:** {plan_goal}\n\n"
        f"**PR:** {pr_url}\n\n"
        f"{diff_summary}\n"
    )
    try:
        if _brain_http:
            _brain_http.call_agent("ingest", f"{adr_path}\n\n{adr_content}")
            print(f"[workshop_push] ADR written: {adr_path}", flush=True)
        else:
            print(
                f"[workshop_push] WARNING: brain_http not available — ADR not written",
                file=sys.stderr,
                flush=True,
            )
    except Exception as exc:
        print(
            f"[workshop_push] WARNING: ADR write-back failed (non-blocking): {exc}",
            file=sys.stderr,
            flush=True,
        )

    print(f"[workshop_push] done — pr_url={pr_url}", flush=True)


if __name__ == "__main__":
    main()
